### ISSUE TITLE
Infinite loop when I add android platform

### ISSUE THREAD

**Issue by leugiim** [imgly/pesdk-cordova-demo#16]
I just download the example and exec: cordova platform add android

![Anotación 2019-07-01 091955](https://user-images.githubusercontent.com/7520601/60418258-c87c1500-9be2-11e9-9555-717a63b8b0df.png)

How can I implement the plugin in my application?

Thank you

**Comment by maltebaumann** [comment]
Hey @leugiim,

You don't need to repeat the steps from within the example app. The app already has the platforms & plugin added. It's now trying to reapply those steps and runs into an infinite loop, because the plugin points to itself at some point.

Instead, repeat the steps within your own project, but be aware that you need to link the plugin from a local directory.

Thanks,
Malte
